### ISSUE TITLE
Is Laravel 5.4 planned to be supported soon?

### ISSUE THREAD

**Issue by uxweb** [squigg/azure-queue-laravel#1]
Hi!

I want to say thanks for been created this package.

Also I want to ask you if there will be a release for Laravel 5.4?

Thanks!

**Comment by squigg** [comment]
I haven't got L5.4 installed yet as I'm still on 5.3. I'll take a look this week and see if there's much work to port it over. Stay tuned!

**Comment by uxweb** [comment]
@squigg

Thank you so much!

**Comment by squigg** [comment]
@uxweb I've now updated the master branch to target 5.4 and pushed a tag for 5.4.*. Should all be available through Composer so give it a try and let me know if any issues.

**Comment by uxweb** [comment]
@squigg 

Thank you! I really appreciate it.
