### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by Stokoe0990** [squigg/azure-queue-laravel#10]
**Summary of issue**
No support for Laravel 6.

This Package: 5.8
Laravel: 6.5
PHP: 7.1 / 7.2 / 7.3
Operating System: Linux

**Comment by squigg** [comment]
I'll see if I can take a look this weekend. Not been following the changes much in L6 so hopefully not too drastic :)

**Comment by goodkenz95** [comment]
Is there possibility for the compatibility for Laravel 6 ? Laravel 5.8 and 6 doesn't really have big changes.

Thanks!

**Comment by squigg** [comment]
Turns out there wasn't much to do, just dependency changes. Should probably have checked that 6 months ago...

6.0.0 tagged just now, 7.0.0 coming shortly :)
