### ISSUE TITLE
Laravel 9

### ISSUE THREAD

**Issue by dieter-pollier** [squigg/azure-queue-laravel#23]
Hi,

Are there any plans to migrate to Laravel 9?

Thanks.

**Comment by squigg** [comment]
Yeh I'll need to see if anything has changed in the Queue APIs. Might get a few hours to look at it this weekend, or I'm open to PRs with any required changes (or just a doc bump if nothing to change)


-------- Original Message --------
From: dieter-pollier ***@***.***>
Sent: 9 March 2022 10:37:25 pm NZDT
To: squigg/azure-queue-laravel ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [squigg/azure-queue-laravel] Laravel 9 (Issue #23)

Hi,

Are there any plans to migrate to Laravel 9?

Thanks.


-- 
Reply to this email directly or view it on GitHub:
https://github.com/squigg/azure-queue-laravel/issues/23

**Comment by mwlvandermaat** [comment]
@squigg Hi,

Are there any plans to migrate to Laravel 10 :D? Would be great ^^

Thanks.
