### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by mwlvandermaat** [squigg/azure-queue-laravel#27]
Hi,

Are there any plans to migrate to Laravel 10?

Thanks.

**Comment by squigg** [comment]
Sorry for the tardy response, I have been looking at it and there appears to be no significant changes. Bumping the deps and just need to run a few integration tests then will push a new version 👍

**Comment by squigg** [comment]
Done! Please give it a try and let me know if any issues.
https://github.com/squigg/azure-queue-laravel/releases/tag/v10.0
